//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.718.0 using the following command:
// XmlSchemaClassGenerator -v -n =QBXML -o "C:\Program Files\Intuit\IDN\Common\tools\validator" --sf -dc --dst --da -gc "C:\Program Files\Intuit\IDN\Common\tools\validator\qbxmlops150.xsd"
namespace QBXML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AppliedToTxnRet", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("AppliedToTxnRet", Namespace="")]
    public partial class AppliedToTxnRet
    {
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(36)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("TxnID")]
        public string TxnID { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("TxnType")]
        public TxnType TxnType { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("TxnDate")]
        public string TxnDate { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(20)]
        [System.Xml.Serialization.XmlElementAttribute("RefNumber")]
        public string RefNumber { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([+\\-]?[0-9]{1,13}(\\.[0-9]{2})?)?")]
        [System.Xml.Serialization.XmlElementAttribute("BalanceRemaining")]
        public string BalanceRemaining { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([+\\-]?[0-9]{1,13}(\\.[0-9]{2})?)?")]
        [System.Xml.Serialization.XmlElementAttribute("Amount")]
        public string Amount { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TxnLineDetail> _txnLineDetail;
        
        [System.Xml.Serialization.XmlElementAttribute("TxnLineDetail")]
        public System.Collections.ObjectModel.Collection<TxnLineDetail> TxnLineDetail
        {
            get
            {
                return _txnLineDetail;
            }
            private set
            {
                _txnLineDetail = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TxnLineDetailSpecified
        {
            get
            {
                return (this.TxnLineDetail.Count != 0);
            }
        }
        
        public AppliedToTxnRet()
        {
            this._txnLineDetail = new System.Collections.ObjectModel.Collection<TxnLineDetail>();
            this._linkedTxn = new System.Collections.ObjectModel.Collection<LinkedTxn>();
        }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([+\\-]?[0-9]{1,13}(\\.[0-9]{2})?)?")]
        [System.Xml.Serialization.XmlElementAttribute("DiscountAmount")]
        public string DiscountAmount { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("DiscountAccountRef")]
        public DiscountAccountRef DiscountAccountRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("DiscountClassRef")]
        public DiscountClassRef DiscountClassRef { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<LinkedTxn> _linkedTxn;
        
        [System.Xml.Serialization.XmlElementAttribute("LinkedTxn")]
        public System.Collections.ObjectModel.Collection<LinkedTxn> LinkedTxn
        {
            get
            {
                return _linkedTxn;
            }
            private set
            {
                _linkedTxn = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LinkedTxnSpecified
        {
            get
            {
                return (this.LinkedTxn.Count != 0);
            }
        }
    }
}
