//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.718.0 using the following command:
// XmlSchemaClassGenerator -v -n =QBXML -o "C:\Program Files\Intuit\IDN\Common\tools\validator" --sf -dc --dst --da -gc "C:\Program Files\Intuit\IDN\Common\tools\validator\qbxmlops150.xsd"
namespace QBXML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BillingRateAdd", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("BillingRateAdd", Namespace="")]
    public partial class BillingRateAdd
    {
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(31)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Name")]
        public string Name { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([+\\-]?[0-9]{1,10}(\\.[0-9]{1,5})?)?")]
        [System.Xml.Serialization.XmlElementAttribute("FixedBillingRate")]
        public string FixedBillingRate { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<BillingRatePerItem> _billingRatePerItem;
        
        [System.Xml.Serialization.XmlElementAttribute("BillingRatePerItem")]
        public System.Collections.ObjectModel.Collection<BillingRatePerItem> BillingRatePerItem
        {
            get
            {
                return _billingRatePerItem;
            }
            private set
            {
                _billingRatePerItem = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BillingRatePerItemSpecified
        {
            get
            {
                return (this.BillingRatePerItem.Count != 0);
            }
        }
        
        public BillingRateAdd()
        {
            this._billingRatePerItem = new System.Collections.ObjectModel.Collection<BillingRatePerItem>();
        }
    }
}
