//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.718.0 using the following command:
// XmlSchemaClassGenerator -v -n =QBXML -o "C:\Program Files\Intuit\IDN\Common\tools\validator" --sf -dc --dst --da -gc "C:\Program Files\Intuit\IDN\Common\tools\validator\qbxmlops150.xsd"
namespace QBXML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BillAdd", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("BillAdd", Namespace="")]
    public partial class BillAdd
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("VendorRef")]
        public VendorRef VendorRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("VendorAddress")]
        public VendorAddress VendorAddress { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("APAccountRef")]
        public APAccountRef APAccountRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("TxnDate")]
        public string TxnDate { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("DueDate")]
        public string DueDate { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(20)]
        [System.Xml.Serialization.XmlElementAttribute("RefNumber")]
        public string RefNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("TermsRef")]
        public TermsRef TermsRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ClassRef")]
        public ClassRef ClassRef { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(4095)]
        [System.Xml.Serialization.XmlElementAttribute("Memo")]
        public string Memo { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IsTaxIncluded")]
        public string IsTaxIncluded { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("SalesTaxCodeRef")]
        public SalesTaxCodeRef SalesTaxCodeRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ExchangeRate")]
        public string ExchangeRate { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|(\\{[0-9a-fA-F]{8}(\\-([0-9a-fA-F]{4})){3}\\-[0-9a-fA-F]{12}\\})")]
        [System.Xml.Serialization.XmlElementAttribute("ExternalGUID")]
        public string ExternalGUID { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _linkToTxnID;
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(36)]
        [System.Xml.Serialization.XmlElementAttribute("LinkToTxnID")]
        public System.Collections.ObjectModel.Collection<string> LinkToTxnID
        {
            get
            {
                return _linkToTxnID;
            }
            private set
            {
                _linkToTxnID = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LinkToTxnIDSpecified
        {
            get
            {
                return (this.LinkToTxnID.Count != 0);
            }
        }
        
        public BillAdd()
        {
            this._linkToTxnID = new System.Collections.ObjectModel.Collection<string>();
            this._expenseLineAdd = new System.Collections.ObjectModel.Collection<ExpenseLineAdd>();
            this._itemLineAdd = new System.Collections.ObjectModel.Collection<ItemLineAdd>();
            this._itemGroupLineAdd = new System.Collections.ObjectModel.Collection<ItemGroupLineAdd>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ExpenseLineAdd> _expenseLineAdd;
        
        [System.Xml.Serialization.XmlElementAttribute("ExpenseLineAdd")]
        public System.Collections.ObjectModel.Collection<ExpenseLineAdd> ExpenseLineAdd
        {
            get
            {
                return _expenseLineAdd;
            }
            private set
            {
                _expenseLineAdd = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpenseLineAddSpecified
        {
            get
            {
                return (this.ExpenseLineAdd.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ItemLineAdd> _itemLineAdd;
        
        [System.Xml.Serialization.XmlElementAttribute("ItemLineAdd")]
        public System.Collections.ObjectModel.Collection<ItemLineAdd> ItemLineAdd
        {
            get
            {
                return _itemLineAdd;
            }
            private set
            {
                _itemLineAdd = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemLineAddSpecified
        {
            get
            {
                return (this.ItemLineAdd.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ItemGroupLineAdd> _itemGroupLineAdd;
        
        [System.Xml.Serialization.XmlElementAttribute("ItemGroupLineAdd")]
        public System.Collections.ObjectModel.Collection<ItemGroupLineAdd> ItemGroupLineAdd
        {
            get
            {
                return _itemGroupLineAdd;
            }
            private set
            {
                _itemGroupLineAdd = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemGroupLineAddSpecified
        {
            get
            {
                return (this.ItemGroupLineAdd.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("defMacro")]
        public string DefMacro { get; set; }
    }
}
