//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.718.0 using the following command:
// XmlSchemaClassGenerator -v -n =QBXML -o "C:\Program Files\Intuit\IDN\Common\tools\validator" --sf -dc --dst --da -gc "C:\Program Files\Intuit\IDN\Common\tools\validator\qbxmlops150.xsd"
namespace QBXML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CompanyRet", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("CompanyRet", Namespace="")]
    public partial class CompanyRet
    {
        
        [System.Xml.Serialization.XmlElementAttribute("IsSampleCompany")]
        public string IsSampleCompany { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(59)]
        [System.Xml.Serialization.XmlElementAttribute("CompanyName")]
        public string CompanyName { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(59)]
        [System.Xml.Serialization.XmlElementAttribute("LegalCompanyName")]
        public string LegalCompanyName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Address")]
        public Address Address { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("AddressBlock")]
        public AddressBlock AddressBlock { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("LegalAddress")]
        public LegalAddress LegalAddress { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("CompanyAddressForCustomer")]
        public CompanyAddressForCustomer CompanyAddressForCustomer { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("CompanyAddressBlockForCustomer")]
        public CompanyAddressBlockForCustomer CompanyAddressBlockForCustomer { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(51)]
        [System.Xml.Serialization.XmlElementAttribute("Phone")]
        public string Phone { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(51)]
        [System.Xml.Serialization.XmlElementAttribute("Fax")]
        public string Fax { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(1023)]
        [System.Xml.Serialization.XmlElementAttribute("Email")]
        public string Email { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("CompanyEmailForCustomer")]
        public string CompanyEmailForCustomer { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(128)]
        [System.Xml.Serialization.XmlElementAttribute("CompanyWebSite")]
        public string CompanyWebSite { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("FirstMonthFiscalYear")]
        public FirstMonthFiscalYear FirstMonthFiscalYear { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FirstMonthFiscalYearSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("FirstMonthIncomeTaxYear")]
        public FirstMonthIncomeTaxYear FirstMonthIncomeTaxYear { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FirstMonthIncomeTaxYearSpecified { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlElementAttribute("CompanyType")]
        public string CompanyType { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(20)]
        [System.Xml.Serialization.XmlElementAttribute("EIN")]
        public string EIN { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(11)]
        [System.Xml.Serialization.XmlElementAttribute("SSN")]
        public string SSN { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("TaxForm")]
        public TaxForm TaxForm { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TaxFormSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Service> _subscribedServices;
        
        [System.Xml.Serialization.XmlArrayAttribute("SubscribedServices")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Service")]
        public System.Collections.ObjectModel.Collection<Service> SubscribedServices
        {
            get
            {
                return _subscribedServices;
            }
            private set
            {
                _subscribedServices = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SubscribedServicesSpecified
        {
            get
            {
                return (this.SubscribedServices.Count != 0);
            }
        }
        
        public CompanyRet()
        {
            this._subscribedServices = new System.Collections.ObjectModel.Collection<Service>();
            this._dataExtRet = new System.Collections.ObjectModel.Collection<DataExtRet>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("AccountantCopy")]
        public AccountantCopy AccountantCopy { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<DataExtRet> _dataExtRet;
        
        [System.Xml.Serialization.XmlElementAttribute("DataExtRet")]
        public System.Collections.ObjectModel.Collection<DataExtRet> DataExtRet
        {
            get
            {
                return _dataExtRet;
            }
            private set
            {
                _dataExtRet = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataExtRetSpecified
        {
            get
            {
                return (this.DataExtRet.Count != 0);
            }
        }
    }
}
