//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.718.0 using the following command:
// XmlSchemaClassGenerator -v -n =QBXML -o "C:\Program Files\Intuit\IDN\Common\tools\validator" --sf -dc --dst --da -gc "C:\Program Files\Intuit\IDN\Common\tools\validator\qbxmlops150.xsd"
namespace QBXML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CreditCardInfo", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("CreditCardInfo", Namespace="")]
    public partial class CreditCardInfo
    {
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(25)]
        [System.Xml.Serialization.XmlElementAttribute("CreditCardNumber")]
        public string CreditCardNumber { get; set; }
        
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(decimal), "1", "12")]
        [System.Xml.Serialization.XmlElementAttribute("ExpirationMonth")]
        public byte ExpirationMonth { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpirationMonthSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ExpirationYear")]
        public string ExpirationYear { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(41)]
        [System.Xml.Serialization.XmlElementAttribute("NameOnCard")]
        public string NameOnCard { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(41)]
        [System.Xml.Serialization.XmlElementAttribute("CreditCardAddress")]
        public string CreditCardAddress { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(41)]
        [System.Xml.Serialization.XmlElementAttribute("CreditCardPostalCode")]
        public string CreditCardPostalCode { get; set; }
    }
}
