//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.718.0 using the following command:
// XmlSchemaClassGenerator -v -n =QBXML -o "C:\Program Files\Intuit\IDN\Common\tools\validator" --sf -dc --dst --da -gc "C:\Program Files\Intuit\IDN\Common\tools\validator\qbxmlops150.xsd"
namespace QBXML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DataExtDefQueryRqType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DataExtDefQueryRqType : global::QBXML.IDataExtDefQuery
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _ownerID;
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|(\\{[0-9a-fA-F]{8}(\\-([0-9a-fA-F]{4})){3}\\-[0-9a-fA-F]{12}\\})")]
        [System.Xml.Serialization.XmlElementAttribute("OwnerID")]
        public System.Collections.ObjectModel.Collection<string> OwnerID
        {
            get
            {
                return _ownerID;
            }
            private set
            {
                _ownerID = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OwnerIDSpecified
        {
            get
            {
                return (this.OwnerID.Count != 0);
            }
        }
        
        public DataExtDefQueryRqType()
        {
            this._ownerID = new System.Collections.ObjectModel.Collection<string>();
            this._assignToObject = new System.Collections.ObjectModel.Collection<global::QBXML.AssignToObject>();
            this._includeRetElement = new System.Collections.ObjectModel.Collection<string>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<global::QBXML.AssignToObject> _assignToObject;
        
        [System.Xml.Serialization.XmlElementAttribute("AssignToObject")]
        public System.Collections.ObjectModel.Collection<global::QBXML.AssignToObject> AssignToObject
        {
            get
            {
                return _assignToObject;
            }
            private set
            {
                _assignToObject = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AssignToObjectSpecified
        {
            get
            {
                return (this.AssignToObject.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _includeRetElement;
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.Xml.Serialization.XmlElementAttribute("IncludeRetElement")]
        public System.Collections.ObjectModel.Collection<string> IncludeRetElement
        {
            get
            {
                return _includeRetElement;
            }
            private set
            {
                _includeRetElement = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IncludeRetElementSpecified
        {
            get
            {
                return (this.IncludeRetElement.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("requestID")]
        public string RequestID { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private DataExtDefQueryRqTypeMetaData _metaData = global::QBXML.DataExtDefQueryRqTypeMetaData.NoMetaData;
        
        [System.ComponentModel.DefaultValueAttribute(global::QBXML.DataExtDefQueryRqTypeMetaData.NoMetaData)]
        [System.Xml.Serialization.XmlAttributeAttribute("metaData")]
        public DataExtDefQueryRqTypeMetaData MetaData
        {
            get
            {
                return _metaData;
            }
            set
            {
                _metaData = value;
            }
        }
    }
}
