//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.718.0 using the following command:
// XmlSchemaClassGenerator -v -n =QBXML -o "C:\Program Files\Intuit\IDN\Common\tools\validator" --sf -dc --dst --da -gc "C:\Program Files\Intuit\IDN\Common\tools\validator\qbxmlops150.xsd"
namespace QBXML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DataEventSubscriptionAdd", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("DataEventSubscriptionAdd", Namespace="")]
    public partial class DataEventSubscriptionAdd
    {
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|(\\{[0-9a-fA-F]{8}(\\-([0-9a-fA-F]{4})){3}\\-[0-9a-fA-F]{12}\\})")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("SubscriberID")]
        public string SubscriberID { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("COMCallbackInfo")]
        public global::QBXML.COMCallbackInfo COMCallbackInfo { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("DeliveryPolicy")]
        public DeliveryPolicy DeliveryPolicy { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("TrackLostEvents")]
        public TrackLostEvents TrackLostEvents { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TrackLostEventsSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("DeliverOwnEvents")]
        public string DeliverOwnEvents { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ListEventSubscription> _listEventSubscription;
        
        [System.Xml.Serialization.XmlElementAttribute("ListEventSubscription")]
        public System.Collections.ObjectModel.Collection<ListEventSubscription> ListEventSubscription
        {
            get
            {
                return _listEventSubscription;
            }
            private set
            {
                _listEventSubscription = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ListEventSubscriptionSpecified
        {
            get
            {
                return (this.ListEventSubscription.Count != 0);
            }
        }
        
        public DataEventSubscriptionAdd()
        {
            this._listEventSubscription = new System.Collections.ObjectModel.Collection<ListEventSubscription>();
            this._txnEventSubscription = new System.Collections.ObjectModel.Collection<TxnEventSubscription>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TxnEventSubscription> _txnEventSubscription;
        
        [System.Xml.Serialization.XmlElementAttribute("TxnEventSubscription")]
        public System.Collections.ObjectModel.Collection<TxnEventSubscription> TxnEventSubscription
        {
            get
            {
                return _txnEventSubscription;
            }
            private set
            {
                _txnEventSubscription = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TxnEventSubscriptionSpecified
        {
            get
            {
                return (this.TxnEventSubscription.Count != 0);
            }
        }
    }
}
