//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.718.0 using the following command:
// XmlSchemaClassGenerator -v -n =QBXML -o "C:\Program Files\Intuit\IDN\Common\tools\validator" --sf -dc --dst --da -gc "C:\Program Files\Intuit\IDN\Common\tools\validator\qbxmlops150.xsd"
namespace QBXML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("EmployeePayrollInfoMod", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("EmployeePayrollInfoMod", Namespace="")]
    public partial class EmployeePayrollInfoMod
    {
        
        [System.Xml.Serialization.XmlElementAttribute("IsCoveredByQualifiedPensionPlan")]
        public string IsCoveredByQualifiedPensionPlan { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("PayPeriod")]
        public PayPeriod PayPeriod { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PayPeriodSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("PayScheduleRef")]
        public PayScheduleRef PayScheduleRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ClassRef")]
        public ClassRef ClassRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ClearEarnings")]
        public string ClearEarnings { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Earnings> _earnings;
        
        [System.Xml.Serialization.XmlElementAttribute("Earnings")]
        public System.Collections.ObjectModel.Collection<Earnings> Earnings
        {
            get
            {
                return _earnings;
            }
            private set
            {
                _earnings = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EarningsSpecified
        {
            get
            {
                return (this.Earnings.Count != 0);
            }
        }
        
        public EmployeePayrollInfoMod()
        {
            this._earnings = new System.Collections.ObjectModel.Collection<Earnings>();
            this._nonEarnings = new System.Collections.ObjectModel.Collection<NonEarnings>();
            this._employeeDirectDepositAccount = new System.Collections.ObjectModel.Collection<EmployeeDirectDepositAccount>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ClearNonEarnings")]
        public string ClearNonEarnings { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<NonEarnings> _nonEarnings;
        
        [System.Xml.Serialization.XmlElementAttribute("NonEarnings")]
        public System.Collections.ObjectModel.Collection<NonEarnings> NonEarnings
        {
            get
            {
                return _nonEarnings;
            }
            private set
            {
                _nonEarnings = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NonEarningsSpecified
        {
            get
            {
                return (this.NonEarnings.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("UseTimeDataToCreatePaychecks")]
        public UseTimeDataToCreatePaychecks UseTimeDataToCreatePaychecks { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UseTimeDataToCreatePaychecksSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("SickHours")]
        public SickHours SickHours { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("VacationHours")]
        public VacationHours VacationHours { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("EmployeeTaxInfo")]
        public EmployeeTaxInfo EmployeeTaxInfo { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("WorkersCompCodeRef")]
        public WorkersCompCodeRef WorkersCompCodeRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ClearDirectDepositAccounts")]
        public string ClearDirectDepositAccounts { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<EmployeeDirectDepositAccount> _employeeDirectDepositAccount;
        
        [System.Xml.Serialization.XmlElementAttribute("EmployeeDirectDepositAccount")]
        public System.Collections.ObjectModel.Collection<EmployeeDirectDepositAccount> EmployeeDirectDepositAccount
        {
            get
            {
                return _employeeDirectDepositAccount;
            }
            private set
            {
                _employeeDirectDepositAccount = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EmployeeDirectDepositAccountSpecified
        {
            get
            {
                return (this.EmployeeDirectDepositAccount.Count != 0);
            }
        }
    }
}
