//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.718.0 using the following command:
// XmlSchemaClassGenerator -v -n =QBXML -o "C:\Program Files\Intuit\IDN\Common\tools\validator" --sf -dc --dst --da -gc "C:\Program Files\Intuit\IDN\Common\tools\validator\qbxmlops150.xsd"
namespace QBXML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("FulfillmentStatus", Namespace="", AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute("FulfillmentStatus", Namespace="")]
    public enum FulfillmentStatus
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("StatusBlank=-1")]
        StatusBlankEqual_1,
        
        [System.Xml.Serialization.XmlEnumAttribute("StatusOpen=0")]
        StatusOpenEqual0,
        
        StatusSentForPick,
        
        StatusPartiallySentForPick,
        
        StatusPickInProgress,
        
        StatusPartialPickInProgress,
        
        StatusPartiallyPicked,
        
        StatusPicked,
        
        StatusPartiallyInvoiced,
        
        StatusInvoiced,
        
        StatusNotPicked,
        
        [System.Xml.Serialization.XmlEnumAttribute("StatusSentForReceive=20")]
        StatusSentForReceiveEqual20,
        
        StatusPartiallySentForReceive,
        
        StatusReceiveInProgress,
        
        StatusPartialReceiveInProgress,
        
        StatusPartiallyReceived,
        
        StatusReceived,
        
        StatusReceiptCreated,
        
        StatusPartialReceiptCreated,
        
        StatusNotReceived,
        
        [System.Xml.Serialization.XmlEnumAttribute("StatusSentForPack=40")]
        StatusSentForPackEqual40,
        
        StatusPartiallySentForPack,
        
        StatusPackInProgress,
        
        StatusPartialPackinProgress,
        
        StatusPartiallyPacked,
        
        StatusPacked,
        
        StatusNotpacked,
        
        [System.Xml.Serialization.XmlEnumAttribute("StatusSentForXpack=50")]
        StatusSentForXpackEqual50,
        
        [System.Xml.Serialization.XmlEnumAttribute("StatusSentForShip=60")]
        StatusSentForShipEqual60,
        
        StatusPartiallySentForShip,
        
        StatusShipInProgress,
        
        StatusPartialShipInProgress,
        
        StatusPartiallyShipped,
        
        StatusStatusShipped,
        
        StatusNotShipped,
        
        [System.Xml.Serialization.XmlEnumAttribute("StatusComplete=100")]
        StatusCompleteEqual100,
    }
}
