//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.718.0 using the following command:
// XmlSchemaClassGenerator -v -n =QBXML -o "C:\Program Files\Intuit\IDN\Common\tools\validator" --sf -dc --dst --da -gc "C:\Program Files\Intuit\IDN\Common\tools\validator\qbxmlops150.xsd"
namespace QBXML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    public partial interface IListQuery : IListFilter
    {
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(36)]
        System.Collections.ObjectModel.Collection<string> ListID
        {
            get;
        }
        
        System.Collections.ObjectModel.Collection<string> FullName
        {
            get;
        }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        System.Collections.ObjectModel.Collection<string> IncludeRetElement
        {
            get;
        }
    }
}
