//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.718.0 using the following command:
// XmlSchemaClassGenerator -v -n =QBXML -o "C:\Program Files\Intuit\IDN\Common\tools\validator" --sf -dc --dst --da -gc "C:\Program Files\Intuit\IDN\Common\tools\validator\qbxmlops150.xsd"
namespace QBXML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("InventoryAdjustmentMod", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("InventoryAdjustmentMod", Namespace="")]
    public partial class InventoryAdjustmentMod : ITxnCoreMod
    {
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(36)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("TxnID")]
        public string TxnID { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(16)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("EditSequence")]
        public string EditSequence { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("AccountRef")]
        public AccountRef AccountRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("InventorySiteRef")]
        public InventorySiteRef InventorySiteRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("TxnDate")]
        public string TxnDate { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(11)]
        [System.Xml.Serialization.XmlElementAttribute("RefNumber")]
        public string RefNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("CustomerRef")]
        public CustomerRef CustomerRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ClassRef")]
        public ClassRef ClassRef { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(4095)]
        [System.Xml.Serialization.XmlElementAttribute("Memo")]
        public string Memo { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<InventoryAdjustmentLineMod> _inventoryAdjustmentLineMod;
        
        [System.Xml.Serialization.XmlElementAttribute("InventoryAdjustmentLineMod")]
        public System.Collections.ObjectModel.Collection<InventoryAdjustmentLineMod> InventoryAdjustmentLineMod
        {
            get
            {
                return _inventoryAdjustmentLineMod;
            }
            private set
            {
                _inventoryAdjustmentLineMod = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InventoryAdjustmentLineModSpecified
        {
            get
            {
                return (this.InventoryAdjustmentLineMod.Count != 0);
            }
        }
        
        public InventoryAdjustmentMod()
        {
            this._inventoryAdjustmentLineMod = new System.Collections.ObjectModel.Collection<InventoryAdjustmentLineMod>();
        }
    }
}
