//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.718.0 using the following command:
// XmlSchemaClassGenerator -v -n =QBXML -o "C:\Program Files\Intuit\IDN\Common\tools\validator" --sf -dc --dst --da -gc "C:\Program Files\Intuit\IDN\Common\tools\validator\qbxmlops150.xsd"
namespace QBXML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("InventoryAdjustmentLineAdd", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("InventoryAdjustmentLineAdd", Namespace="")]
    public partial class InventoryAdjustmentLineAdd
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ItemRef")]
        public ItemRef ItemRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("QuantityAdjustment")]
        public QuantityAdjustment QuantityAdjustment { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ValueAdjustment")]
        public ValueAdjustment ValueAdjustment { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("SerialNumberAdjustment")]
        public SerialNumberAdjustment SerialNumberAdjustment { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("LotNumberAdjustment")]
        public LotNumberAdjustment LotNumberAdjustment { get; set; }
    }
}
