//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.718.0 using the following command:
// XmlSchemaClassGenerator -v -n =QBXML -o "C:\Program Files\Intuit\IDN\Common\tools\validator" --sf -dc --dst --da -gc "C:\Program Files\Intuit\IDN\Common\tools\validator\qbxmlops150.xsd"
namespace QBXML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    public partial interface IPersonName
    {
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(15)]
        string Salutation
        {
            get;
            set;
        }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(25)]
        string FirstName
        {
            get;
            set;
        }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(5)]
        string MiddleName
        {
            get;
            set;
        }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(25)]
        string LastName
        {
            get;
            set;
        }
        
        string Suffix
        {
            get;
            set;
        }
    }
}
