//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.718.0 using the following command:
// XmlSchemaClassGenerator -v -n =QBXML -o "C:\Program Files\Intuit\IDN\Common\tools\validator" --sf -dc --dst --da -gc "C:\Program Files\Intuit\IDN\Common\tools\validator\qbxmlops150.xsd"
namespace QBXML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    public partial interface ISiteAddressData
    {
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(41)]
        string Addr1
        {
            get;
            set;
        }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(41)]
        string Addr2
        {
            get;
            set;
        }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(41)]
        string Addr3
        {
            get;
            set;
        }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(41)]
        string Addr4
        {
            get;
            set;
        }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(41)]
        string Addr5
        {
            get;
            set;
        }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(31)]
        string City
        {
            get;
            set;
        }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(21)]
        string State
        {
            get;
            set;
        }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(13)]
        string PostalCode
        {
            get;
            set;
        }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(31)]
        string Country
        {
            get;
            set;
        }
    }
}
