//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.718.0 using the following command:
// XmlSchemaClassGenerator -v -n =QBXML -o "C:\Program Files\Intuit\IDN\Common\tools\validator" --sf -dc --dst --da -gc "C:\Program Files\Intuit\IDN\Common\tools\validator\qbxmlops150.xsd"
namespace QBXML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ItemInventoryAssemblyAdd", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ItemInventoryAssemblyAdd", Namespace="")]
    public partial class ItemInventoryAssemblyAdd
    {
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(31)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Name")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("BarCode")]
        public BarCode BarCode { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IsActive")]
        public string IsActive { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ClassRef")]
        public ClassRef ClassRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ParentRef")]
        public ParentRef ParentRef { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(31)]
        [System.Xml.Serialization.XmlElementAttribute("ManufacturerPartNumber")]
        public string ManufacturerPartNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("UnitOfMeasureSetRef")]
        public UnitOfMeasureSetRef UnitOfMeasureSetRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IsTaxIncluded")]
        public string IsTaxIncluded { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("SalesTaxCodeRef")]
        public SalesTaxCodeRef SalesTaxCodeRef { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(4095)]
        [System.Xml.Serialization.XmlElementAttribute("SalesDesc")]
        public string SalesDesc { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([+\\-]?[0-9]{1,10}(\\.[0-9]{1,5})?)?")]
        [System.Xml.Serialization.XmlElementAttribute("SalesPrice")]
        public string SalesPrice { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IncomeAccountRef")]
        public IncomeAccountRef IncomeAccountRef { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(4095)]
        [System.Xml.Serialization.XmlElementAttribute("PurchaseDesc")]
        public string PurchaseDesc { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([+\\-]?[0-9]{1,10}(\\.[0-9]{1,5})?)?")]
        [System.Xml.Serialization.XmlElementAttribute("PurchaseCost")]
        public string PurchaseCost { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("PurchaseTaxCodeRef")]
        public PurchaseTaxCodeRef PurchaseTaxCodeRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("COGSAccountRef")]
        public COGSAccountRef COGSAccountRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("PrefVendorRef")]
        public PrefVendorRef PrefVendorRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("AssetAccountRef")]
        public AssetAccountRef AssetAccountRef { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([+\\-]?[0-9]{1,10}(\\.[0-9]{1,5})?)?")]
        [System.Xml.Serialization.XmlElementAttribute("BuildPoint")]
        public string BuildPoint { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([+\\-]?[0-9]{1,10}(\\.[0-9]{1,5})?)?")]
        [System.Xml.Serialization.XmlElementAttribute("Max")]
        public string Max { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([+\\-]?[0-9]{1,10}(\\.[0-9]{1,5})?)?")]
        [System.Xml.Serialization.XmlElementAttribute("QuantityOnHand")]
        public string QuantityOnHand { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([+\\-]?[0-9]{1,13}(\\.[0-9]{2})?)?")]
        [System.Xml.Serialization.XmlElementAttribute("TotalValue")]
        public string TotalValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("InventoryDate")]
        public string InventoryDate { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|(\\{[0-9a-fA-F]{8}(\\-([0-9a-fA-F]{4})){3}\\-[0-9a-fA-F]{12}\\})")]
        [System.Xml.Serialization.XmlElementAttribute("ExternalGUID")]
        public string ExternalGUID { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ItemInventoryAssemblyLine> _itemInventoryAssemblyLine;
        
        [System.Xml.Serialization.XmlElementAttribute("ItemInventoryAssemblyLine")]
        public System.Collections.ObjectModel.Collection<ItemInventoryAssemblyLine> ItemInventoryAssemblyLine
        {
            get
            {
                return _itemInventoryAssemblyLine;
            }
            private set
            {
                _itemInventoryAssemblyLine = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemInventoryAssemblyLineSpecified
        {
            get
            {
                return (this.ItemInventoryAssemblyLine.Count != 0);
            }
        }
        
        public ItemInventoryAssemblyAdd()
        {
            this._itemInventoryAssemblyLine = new System.Collections.ObjectModel.Collection<ItemInventoryAssemblyLine>();
        }
    }
}
