//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.718.0 using the following command:
// XmlSchemaClassGenerator -v -n =QBXML -o "C:\Program Files\Intuit\IDN\Common\tools\validator" --sf -dc --dst --da -gc "C:\Program Files\Intuit\IDN\Common\tools\validator\qbxmlops150.xsd"
namespace QBXML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ItemGroupMod", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ItemGroupMod", Namespace="")]
    public partial class ItemGroupMod : IListCoreMod
    {
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(36)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ListID")]
        public string ListID { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(16)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("EditSequence")]
        public string EditSequence { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(31)]
        [System.Xml.Serialization.XmlElementAttribute("Name")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("BarCode")]
        public BarCode BarCode { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IsActive")]
        public string IsActive { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(4095)]
        [System.Xml.Serialization.XmlElementAttribute("ItemDesc")]
        public string ItemDesc { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("UnitOfMeasureSetRef")]
        public UnitOfMeasureSetRef UnitOfMeasureSetRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ForceUOMChange")]
        public string ForceUOMChange { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IsPrintItemsInGroup")]
        public string IsPrintItemsInGroup { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ClearItemsInGroup")]
        public string ClearItemsInGroup { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ItemGroupLine> _itemGroupLine;
        
        [System.Xml.Serialization.XmlElementAttribute("ItemGroupLine")]
        public System.Collections.ObjectModel.Collection<ItemGroupLine> ItemGroupLine
        {
            get
            {
                return _itemGroupLine;
            }
            private set
            {
                _itemGroupLine = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemGroupLineSpecified
        {
            get
            {
                return (this.ItemGroupLine.Count != 0);
            }
        }
        
        public ItemGroupMod()
        {
            this._itemGroupLine = new System.Collections.ObjectModel.Collection<ItemGroupLine>();
        }
    }
}
