//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.718.0 using the following command:
// XmlSchemaClassGenerator -v -n =QBXML -o "C:\Program Files\Intuit\IDN\Common\tools\validator" --sf -dc --dst --da -gc "C:\Program Files\Intuit\IDN\Common\tools\validator\qbxmlops150.xsd"
namespace QBXML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LeadRet", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("LeadRet", Namespace="")]
    public partial class LeadRet : IListCore
    {
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(36)]
        [System.Xml.Serialization.XmlElementAttribute("ListID")]
        public string ListID { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([0-9]{4}\\-[0-9]{1,2}\\-[0-9]{1,2}(T[0-9]{1,2}(:[0-9]{1,2}(:[0-9]{1,2}([+\\-]{1}[0-" +
            "9]{1,2}:[0-9]{1,2})?)?)?)?)?")]
        [System.Xml.Serialization.XmlElementAttribute("TimeCreated")]
        public string TimeCreated { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([0-9]{4}\\-[0-9]{1,2}\\-[0-9]{1,2}(T[0-9]{1,2}(:[0-9]{1,2}(:[0-9]{1,2}([+\\-]{1}[0-" +
            "9]{1,2}:[0-9]{1,2})?)?)?)?)?")]
        [System.Xml.Serialization.XmlElementAttribute("TimeModified")]
        public string TimeModified { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(16)]
        [System.Xml.Serialization.XmlElementAttribute("EditSequence")]
        public string EditSequence { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(41)]
        [System.Xml.Serialization.XmlElementAttribute("FullName")]
        public string FullName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Status")]
        public Status Status { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(41)]
        [System.Xml.Serialization.XmlElementAttribute("CompanyName")]
        public string CompanyName { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(21)]
        [System.Xml.Serialization.XmlElementAttribute("MainPhone")]
        public string MainPhone { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AdditionalContactRef> _additionalContactRef;
        
        [System.Xml.Serialization.XmlElementAttribute("AdditionalContactRef")]
        public System.Collections.ObjectModel.Collection<AdditionalContactRef> AdditionalContactRef
        {
            get
            {
                return _additionalContactRef;
            }
            private set
            {
                _additionalContactRef = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdditionalContactRefSpecified
        {
            get
            {
                return (this.AdditionalContactRef.Count != 0);
            }
        }
        
        public LeadRet()
        {
            this._additionalContactRef = new System.Collections.ObjectModel.Collection<AdditionalContactRef>();
            this._locationsRet = new System.Collections.ObjectModel.Collection<LocationsRet>();
            this._leadContactsRet = new System.Collections.ObjectModel.Collection<LeadContactsRet>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<LocationsRet> _locationsRet;
        
        [System.Xml.Serialization.XmlElementAttribute("LocationsRet")]
        public System.Collections.ObjectModel.Collection<LocationsRet> LocationsRet
        {
            get
            {
                return _locationsRet;
            }
            private set
            {
                _locationsRet = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LocationsRetSpecified
        {
            get
            {
                return (this.LocationsRet.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<LeadContactsRet> _leadContactsRet;
        
        [System.Xml.Serialization.XmlElementAttribute("LeadContactsRet")]
        public System.Collections.ObjectModel.Collection<LeadContactsRet> LeadContactsRet
        {
            get
            {
                return _leadContactsRet;
            }
            private set
            {
                _leadContactsRet = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LeadContactsRetSpecified
        {
            get
            {
                return (this.LeadContactsRet.Count != 0);
            }
        }
    }
}
