//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.718.0 using the following command:
// XmlSchemaClassGenerator -v -n =QBXML -o "C:\Program Files\Intuit\IDN\Common\tools\validator" --sf -dc --dst --da -gc "C:\Program Files\Intuit\IDN\Common\tools\validator\qbxmlops150.xsd"
namespace QBXML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PayrollLiabilityAdjustmentAdd", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("PayrollLiabilityAdjustmentAdd", Namespace="")]
    public partial class PayrollLiabilityAdjustmentAdd
    {
        
        [System.Xml.Serialization.XmlElementAttribute("AccountRef")]
        public AccountRef AccountRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("EmployeeRef")]
        public EmployeeRef EmployeeRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ClassRef")]
        public ClassRef ClassRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("TxnDate")]
        public string TxnDate { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(11)]
        [System.Xml.Serialization.XmlElementAttribute("RefNumber")]
        public string RefNumber { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(4095)]
        [System.Xml.Serialization.XmlElementAttribute("Memo")]
        public string Memo { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("IsAffectingAccounts")]
        public string IsAffectingAccounts { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("PayrollDate")]
        public string PayrollDate { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("TaxTableVersion")]
        public string TaxTableVersion { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PayrollLiabilityAdjustmentLineAdd> _payrollLiabilityAdjustmentLineAdd;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("PayrollLiabilityAdjustmentLineAdd")]
        public System.Collections.ObjectModel.Collection<PayrollLiabilityAdjustmentLineAdd> PayrollLiabilityAdjustmentLineAdd
        {
            get
            {
                return _payrollLiabilityAdjustmentLineAdd;
            }
            private set
            {
                _payrollLiabilityAdjustmentLineAdd = value;
            }
        }
        
        public PayrollLiabilityAdjustmentAdd()
        {
            this._payrollLiabilityAdjustmentLineAdd = new System.Collections.ObjectModel.Collection<PayrollLiabilityAdjustmentLineAdd>();
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("defMacro")]
        public string DefMacro { get; set; }
    }
}
