//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.718.0 using the following command:
// XmlSchemaClassGenerator -v -n =QBXML -o "C:\Program Files\Intuit\IDN\Common\tools\validator" --sf -dc --dst --da -gc "C:\Program Files\Intuit\IDN\Common\tools\validator\qbxmlops150.xsd"
namespace QBXML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PayrollPriorPaymentQueryRqType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PayrollPriorPaymentQueryRqType : global::QBXML.IPayrollTxnQuery
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _txnID;
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(36)]
        [System.Xml.Serialization.XmlElementAttribute("TxnID")]
        public System.Collections.ObjectModel.Collection<string> TxnID
        {
            get
            {
                return _txnID;
            }
            private set
            {
                _txnID = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TxnIDSpecified
        {
            get
            {
                return (this.TxnID.Count != 0);
            }
        }
        
        public PayrollPriorPaymentQueryRqType()
        {
            this._txnID = new System.Collections.ObjectModel.Collection<string>();
            this._refNumber = new System.Collections.ObjectModel.Collection<string>();
            this._refNumberCaseSensitive = new System.Collections.ObjectModel.Collection<string>();
            this._includeRetElement = new System.Collections.ObjectModel.Collection<string>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _refNumber;
        
        [System.Xml.Serialization.XmlElementAttribute("RefNumber")]
        public System.Collections.ObjectModel.Collection<string> RefNumber
        {
            get
            {
                return _refNumber;
            }
            private set
            {
                _refNumber = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RefNumberSpecified
        {
            get
            {
                return (this.RefNumber.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _refNumberCaseSensitive;
        
        [System.Xml.Serialization.XmlElementAttribute("RefNumberCaseSensitive")]
        public System.Collections.ObjectModel.Collection<string> RefNumberCaseSensitive
        {
            get
            {
                return _refNumberCaseSensitive;
            }
            private set
            {
                _refNumberCaseSensitive = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RefNumberCaseSensitiveSpecified
        {
            get
            {
                return (this.RefNumberCaseSensitive.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("MaxReturned")]
        public string MaxReturned { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ModifiedDateRangeFilter")]
        public global::QBXML.ModifiedDateRangeFilter ModifiedDateRangeFilter { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("TxnDateRangeFilter")]
        public global::QBXML.TxnDateRangeFilter TxnDateRangeFilter { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("PayrollDateRangeFilter")]
        public global::QBXML.PayrollDateRangeFilter PayrollDateRangeFilter { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("EntityFilter")]
        public global::QBXML.EntityFilter EntityFilter { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("AccountFilter")]
        public global::QBXML.AccountFilter AccountFilter { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("RefNumberFilter")]
        public global::QBXML.RefNumberFilter RefNumberFilter { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("RefNumberRangeFilter")]
        public global::QBXML.RefNumberRangeFilter RefNumberRangeFilter { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IncludeLineItems")]
        public string IncludeLineItems { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _includeRetElement;
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.Xml.Serialization.XmlElementAttribute("IncludeRetElement")]
        public System.Collections.ObjectModel.Collection<string> IncludeRetElement
        {
            get
            {
                return _includeRetElement;
            }
            private set
            {
                _includeRetElement = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IncludeRetElementSpecified
        {
            get
            {
                return (this.IncludeRetElement.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("requestID")]
        public string RequestID { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private PayrollPriorPaymentQueryRqTypeMetaData _metaData = global::QBXML.PayrollPriorPaymentQueryRqTypeMetaData.NoMetaData;
        
        [System.ComponentModel.DefaultValueAttribute(global::QBXML.PayrollPriorPaymentQueryRqTypeMetaData.NoMetaData)]
        [System.Xml.Serialization.XmlAttributeAttribute("metaData")]
        public PayrollPriorPaymentQueryRqTypeMetaData MetaData
        {
            get
            {
                return _metaData;
            }
            set
            {
                _metaData = value;
            }
        }
    }
}
