//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.718.0 using the following command:
// XmlSchemaClassGenerator -v -n =QBXML -o "C:\Program Files\Intuit\IDN\Common\tools\validator" --sf -dc --dst --da -gc "C:\Program Files\Intuit\IDN\Common\tools\validator\qbxmlops150.xsd"
namespace QBXML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PreferencesRet", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("PreferencesRet", Namespace="")]
    public partial class PreferencesRet
    {
        
        [System.Xml.Serialization.XmlElementAttribute("AccountingPreferences")]
        public AccountingPreferences AccountingPreferences { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("FinanceChargePreferences")]
        public FinanceChargePreferences FinanceChargePreferences { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("JobsAndEstimatesPreferences")]
        public JobsAndEstimatesPreferences JobsAndEstimatesPreferences { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("MultiCurrencyPreferences")]
        public MultiCurrencyPreferences MultiCurrencyPreferences { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("MultiLocationInventoryPreferences")]
        public MultiLocationInventoryPreferences MultiLocationInventoryPreferences { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("PurchasesAndVendorsPreferences")]
        public PurchasesAndVendorsPreferences PurchasesAndVendorsPreferences { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ReportsPreferences")]
        public ReportsPreferences ReportsPreferences { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("SalesAndCustomersPreferences")]
        public SalesAndCustomersPreferences SalesAndCustomersPreferences { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("SalesTaxPreferences")]
        public SalesTaxPreferences SalesTaxPreferences { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("TimeTrackingPreferences")]
        public TimeTrackingPreferences TimeTrackingPreferences { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("CurrentAppAccessRights")]
        public CurrentAppAccessRights CurrentAppAccessRights { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ItemsAndInventoryPreferences")]
        public ItemsAndInventoryPreferences ItemsAndInventoryPreferences { get; set; }
    }
}
