//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.718.0 using the following command:
// XmlSchemaClassGenerator -v -n =QBXML -o "C:\Program Files\Intuit\IDN\Common\tools\validator" --sf -dc --dst --da -gc "C:\Program Files\Intuit\IDN\Common\tools\validator\qbxmlops150.xsd"
namespace QBXML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PurchaseOrderMod", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("PurchaseOrderMod", Namespace="")]
    public partial class PurchaseOrderMod
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("TxnID")]
        public PurchaseOrderModTxnID TxnID { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(16)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("EditSequence")]
        public string EditSequence { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("VendorRef")]
        public VendorRef VendorRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ClassRef")]
        public ClassRef ClassRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("InventorySiteRef")]
        public InventorySiteRef InventorySiteRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ShipToEntityRef")]
        public ShipToEntityRef ShipToEntityRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("TemplateRef")]
        public TemplateRef TemplateRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("TxnDate")]
        public string TxnDate { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(11)]
        [System.Xml.Serialization.XmlElementAttribute("RefNumber")]
        public string RefNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("VendorAddress")]
        public VendorAddress VendorAddress { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ShipAddress")]
        public ShipAddress ShipAddress { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("TermsRef")]
        public TermsRef TermsRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("DueDate")]
        public string DueDate { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ExpectedDate")]
        public string ExpectedDate { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ShipMethodRef")]
        public ShipMethodRef ShipMethodRef { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(13)]
        [System.Xml.Serialization.XmlElementAttribute("FOB")]
        public string FOB { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IsManuallyClosed")]
        public string IsManuallyClosed { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(4095)]
        [System.Xml.Serialization.XmlElementAttribute("Memo")]
        public string Memo { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(99)]
        [System.Xml.Serialization.XmlElementAttribute("VendorMsg")]
        public string VendorMsg { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IsToBePrinted")]
        public string IsToBePrinted { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IsToBeEmailed")]
        public string IsToBeEmailed { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IsTaxIncluded")]
        public string IsTaxIncluded { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("SalesTaxCodeRef")]
        public SalesTaxCodeRef SalesTaxCodeRef { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(25)]
        [System.Xml.Serialization.XmlElementAttribute("Other1")]
        public string Other1 { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(29)]
        [System.Xml.Serialization.XmlElementAttribute("Other2")]
        public string Other2 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ExchangeRate")]
        public string ExchangeRate { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PurchaseOrderLineMod> _purchaseOrderLineMod;
        
        [System.Xml.Serialization.XmlElementAttribute("PurchaseOrderLineMod")]
        public System.Collections.ObjectModel.Collection<PurchaseOrderLineMod> PurchaseOrderLineMod
        {
            get
            {
                return _purchaseOrderLineMod;
            }
            private set
            {
                _purchaseOrderLineMod = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PurchaseOrderLineModSpecified
        {
            get
            {
                return (this.PurchaseOrderLineMod.Count != 0);
            }
        }
        
        public PurchaseOrderMod()
        {
            this._purchaseOrderLineMod = new System.Collections.ObjectModel.Collection<PurchaseOrderLineMod>();
            this._purchaseOrderLineGroupMod = new System.Collections.ObjectModel.Collection<PurchaseOrderLineGroupMod>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PurchaseOrderLineGroupMod> _purchaseOrderLineGroupMod;
        
        [System.Xml.Serialization.XmlElementAttribute("PurchaseOrderLineGroupMod")]
        public System.Collections.ObjectModel.Collection<PurchaseOrderLineGroupMod> PurchaseOrderLineGroupMod
        {
            get
            {
                return _purchaseOrderLineGroupMod;
            }
            private set
            {
                _purchaseOrderLineGroupMod = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PurchaseOrderLineGroupModSpecified
        {
            get
            {
                return (this.PurchaseOrderLineGroupMod.Count != 0);
            }
        }
    }
}
