//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.718.0 using the following command:
// XmlSchemaClassGenerator -v -n =QBXML -o "C:\Program Files\Intuit\IDN\Common\tools\validator" --sf -dc --dst --da -gc "C:\Program Files\Intuit\IDN\Common\tools\validator\qbxmlops150.xsd"
namespace QBXML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("QBXMLSubscriptionMsgsRs", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("QBXMLSubscriptionMsgsRs", Namespace="")]
    public partial class QBXMLSubscriptionMsgsRs
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<DataEventSubscriptionAddRsType> _dataEventSubscriptionAddRs;
        
        [System.Xml.Serialization.XmlElementAttribute("DataEventSubscriptionAddRs")]
        public System.Collections.ObjectModel.Collection<DataEventSubscriptionAddRsType> DataEventSubscriptionAddRs
        {
            get
            {
                return _dataEventSubscriptionAddRs;
            }
            private set
            {
                _dataEventSubscriptionAddRs = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataEventSubscriptionAddRsSpecified
        {
            get
            {
                return (this.DataEventSubscriptionAddRs.Count != 0);
            }
        }
        
        public QBXMLSubscriptionMsgsRs()
        {
            this._dataEventSubscriptionAddRs = new System.Collections.ObjectModel.Collection<DataEventSubscriptionAddRsType>();
            this._dataEventSubscriptionQueryRs = new System.Collections.ObjectModel.Collection<DataEventSubscriptionQueryRsType>();
            this._uIEventSubscriptionAddRs = new System.Collections.ObjectModel.Collection<UIEventSubscriptionAddRsType>();
            this._uIEventSubscriptionQueryRs = new System.Collections.ObjectModel.Collection<UIEventSubscriptionQueryRsType>();
            this._uIExtensionSubscriptionAddRs = new System.Collections.ObjectModel.Collection<UIExtensionSubscriptionAddRsType>();
            this._uIExtensionSubscriptionQueryRs = new System.Collections.ObjectModel.Collection<UIExtensionSubscriptionQueryRsType>();
            this._subscriptionDelRs = new System.Collections.ObjectModel.Collection<SubscriptionDelRsType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<DataEventSubscriptionQueryRsType> _dataEventSubscriptionQueryRs;
        
        [System.Xml.Serialization.XmlElementAttribute("DataEventSubscriptionQueryRs")]
        public System.Collections.ObjectModel.Collection<DataEventSubscriptionQueryRsType> DataEventSubscriptionQueryRs
        {
            get
            {
                return _dataEventSubscriptionQueryRs;
            }
            private set
            {
                _dataEventSubscriptionQueryRs = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataEventSubscriptionQueryRsSpecified
        {
            get
            {
                return (this.DataEventSubscriptionQueryRs.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<UIEventSubscriptionAddRsType> _uIEventSubscriptionAddRs;
        
        [System.Xml.Serialization.XmlElementAttribute("UIEventSubscriptionAddRs")]
        public System.Collections.ObjectModel.Collection<UIEventSubscriptionAddRsType> UIEventSubscriptionAddRs
        {
            get
            {
                return _uIEventSubscriptionAddRs;
            }
            private set
            {
                _uIEventSubscriptionAddRs = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UIEventSubscriptionAddRsSpecified
        {
            get
            {
                return (this.UIEventSubscriptionAddRs.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<UIEventSubscriptionQueryRsType> _uIEventSubscriptionQueryRs;
        
        [System.Xml.Serialization.XmlElementAttribute("UIEventSubscriptionQueryRs")]
        public System.Collections.ObjectModel.Collection<UIEventSubscriptionQueryRsType> UIEventSubscriptionQueryRs
        {
            get
            {
                return _uIEventSubscriptionQueryRs;
            }
            private set
            {
                _uIEventSubscriptionQueryRs = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UIEventSubscriptionQueryRsSpecified
        {
            get
            {
                return (this.UIEventSubscriptionQueryRs.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<UIExtensionSubscriptionAddRsType> _uIExtensionSubscriptionAddRs;
        
        [System.Xml.Serialization.XmlElementAttribute("UIExtensionSubscriptionAddRs")]
        public System.Collections.ObjectModel.Collection<UIExtensionSubscriptionAddRsType> UIExtensionSubscriptionAddRs
        {
            get
            {
                return _uIExtensionSubscriptionAddRs;
            }
            private set
            {
                _uIExtensionSubscriptionAddRs = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UIExtensionSubscriptionAddRsSpecified
        {
            get
            {
                return (this.UIExtensionSubscriptionAddRs.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<UIExtensionSubscriptionQueryRsType> _uIExtensionSubscriptionQueryRs;
        
        [System.Xml.Serialization.XmlElementAttribute("UIExtensionSubscriptionQueryRs")]
        public System.Collections.ObjectModel.Collection<UIExtensionSubscriptionQueryRsType> UIExtensionSubscriptionQueryRs
        {
            get
            {
                return _uIExtensionSubscriptionQueryRs;
            }
            private set
            {
                _uIExtensionSubscriptionQueryRs = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UIExtensionSubscriptionQueryRsSpecified
        {
            get
            {
                return (this.UIExtensionSubscriptionQueryRs.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<SubscriptionDelRsType> _subscriptionDelRs;
        
        [System.Xml.Serialization.XmlElementAttribute("SubscriptionDelRs")]
        public System.Collections.ObjectModel.Collection<SubscriptionDelRsType> SubscriptionDelRs
        {
            get
            {
                return _subscriptionDelRs;
            }
            private set
            {
                _subscriptionDelRs = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SubscriptionDelRsSpecified
        {
            get
            {
                return (this.SubscriptionDelRs.Count != 0);
            }
        }
    }
}
