//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.718.0 using the following command:
// XmlSchemaClassGenerator -v -n =QBXML -o "C:\Program Files\Intuit\IDN\Common\tools\validator" --sf -dc --dst --da -gc "C:\Program Files\Intuit\IDN\Common\tools\validator\qbxmlops150.xsd"
namespace QBXML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SalesTaxReturnLineQueryRqType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SalesTaxReturnLineQueryRqType : global::QBXML.ISalesTaxReturnLineQuery
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<global::QBXML.TaxAgencyVendorRef> _taxAgencyVendorRef;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("TaxAgencyVendorRef")]
        public System.Collections.ObjectModel.Collection<global::QBXML.TaxAgencyVendorRef> TaxAgencyVendorRef
        {
            get
            {
                return _taxAgencyVendorRef;
            }
            private set
            {
                _taxAgencyVendorRef = value;
            }
        }
        
        public SalesTaxReturnLineQueryRqType()
        {
            this._taxAgencyVendorRef = new System.Collections.ObjectModel.Collection<global::QBXML.TaxAgencyVendorRef>();
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("requestID")]
        public string RequestID { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private SalesTaxReturnLineQueryRqTypeMetaData _metaData = global::QBXML.SalesTaxReturnLineQueryRqTypeMetaData.NoMetaData;
        
        [System.ComponentModel.DefaultValueAttribute(global::QBXML.SalesTaxReturnLineQueryRqTypeMetaData.NoMetaData)]
        [System.Xml.Serialization.XmlAttributeAttribute("metaData")]
        public SalesTaxReturnLineQueryRqTypeMetaData MetaData
        {
            get
            {
                return _metaData;
            }
            set
            {
                _metaData = value;
            }
        }
    }
}
