//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.718.0 using the following command:
// XmlSchemaClassGenerator -v -n =QBXML -o "C:\Program Files\Intuit\IDN\Common\tools\validator" --sf -dc --dst --da -gc "C:\Program Files\Intuit\IDN\Common\tools\validator\qbxmlops150.xsd"
namespace QBXML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SalesOrderRet", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("SalesOrderRet", Namespace="")]
    public partial class SalesOrderRet : ITxnCore, ITxnFieldsCore, ISalesTaxData
    {
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(36)]
        [System.Xml.Serialization.XmlElementAttribute("TxnID")]
        public string TxnID { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([0-9]{4}\\-[0-9]{1,2}\\-[0-9]{1,2}(T[0-9]{1,2}(:[0-9]{1,2}(:[0-9]{1,2}([+\\-]{1}[0-" +
            "9]{1,2}:[0-9]{1,2})?)?)?)?)?")]
        [System.Xml.Serialization.XmlElementAttribute("TimeCreated")]
        public string TimeCreated { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([0-9]{4}\\-[0-9]{1,2}\\-[0-9]{1,2}(T[0-9]{1,2}(:[0-9]{1,2}(:[0-9]{1,2}([+\\-]{1}[0-" +
            "9]{1,2}:[0-9]{1,2})?)?)?)?)?")]
        [System.Xml.Serialization.XmlElementAttribute("TimeModified")]
        public string TimeModified { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(16)]
        [System.Xml.Serialization.XmlElementAttribute("EditSequence")]
        public string EditSequence { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("TxnNumber")]
        public string TxnNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("CustomerRef")]
        public CustomerRef CustomerRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ClassRef")]
        public ClassRef ClassRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("TemplateRef")]
        public TemplateRef TemplateRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("TxnDate")]
        public string TxnDate { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(11)]
        [System.Xml.Serialization.XmlElementAttribute("RefNumber")]
        public string RefNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("BillAddress")]
        public BillAddress BillAddress { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("BillAddressBlock")]
        public BillAddressBlock BillAddressBlock { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ShipAddress")]
        public ShipAddress ShipAddress { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ShipAddressBlock")]
        public ShipAddressBlock ShipAddressBlock { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(25)]
        [System.Xml.Serialization.XmlElementAttribute("PONumber")]
        public string PONumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("TermsRef")]
        public TermsRef TermsRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("DueDate")]
        public string DueDate { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("SalesRepRef")]
        public SalesRepRef SalesRepRef { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(13)]
        [System.Xml.Serialization.XmlElementAttribute("FOB")]
        public string FOB { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ShipDate")]
        public string ShipDate { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ShipMethodRef")]
        public ShipMethodRef ShipMethodRef { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([+\\-]?[0-9]{1,13}(\\.[0-9]{2})?)?")]
        [System.Xml.Serialization.XmlElementAttribute("Subtotal")]
        public string Subtotal { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ItemSalesTaxRef")]
        public ItemSalesTaxRef ItemSalesTaxRef { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([+\\-]?[0-9]{1,10}(\\.[0-9]{1,5})?)?")]
        [System.Xml.Serialization.XmlElementAttribute("SalesTaxPercentage")]
        public string SalesTaxPercentage { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([+\\-]?[0-9]{1,13}(\\.[0-9]{2})?)?")]
        [System.Xml.Serialization.XmlElementAttribute("SalesTaxTotal")]
        public string SalesTaxTotal { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([+\\-]?[0-9]{1,13}(\\.[0-9]{2})?)?")]
        [System.Xml.Serialization.XmlElementAttribute("TotalAmount")]
        public string TotalAmount { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("CurrencyRef")]
        public CurrencyRef CurrencyRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ExchangeRate")]
        public string ExchangeRate { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([+\\-]?[0-9]{1,13}(\\.[0-9]{2})?)?")]
        [System.Xml.Serialization.XmlElementAttribute("TotalAmountInHomeCurrency")]
        public string TotalAmountInHomeCurrency { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IsManuallyClosed")]
        public string IsManuallyClosed { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IsFullyInvoiced")]
        public string IsFullyInvoiced { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(4095)]
        [System.Xml.Serialization.XmlElementAttribute("Memo")]
        public string Memo { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("CustomerMsgRef")]
        public CustomerMsgRef CustomerMsgRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IsToBePrinted")]
        public string IsToBePrinted { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IsToBeEmailed")]
        public string IsToBeEmailed { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IsTaxIncluded")]
        public string IsTaxIncluded { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("CustomerSalesTaxCodeRef")]
        public CustomerSalesTaxCodeRef CustomerSalesTaxCodeRef { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(29)]
        [System.Xml.Serialization.XmlElementAttribute("Other")]
        public string Other { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|(\\{[0-9a-fA-F]{8}(\\-([0-9a-fA-F]{4})){3}\\-[0-9a-fA-F]{12}\\})")]
        [System.Xml.Serialization.XmlElementAttribute("ExternalGUID")]
        public string ExternalGUID { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<LinkedTxn> _linkedTxn;
        
        [System.Xml.Serialization.XmlElementAttribute("LinkedTxn")]
        public System.Collections.ObjectModel.Collection<LinkedTxn> LinkedTxn
        {
            get
            {
                return _linkedTxn;
            }
            private set
            {
                _linkedTxn = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LinkedTxnSpecified
        {
            get
            {
                return (this.LinkedTxn.Count != 0);
            }
        }
        
        public SalesOrderRet()
        {
            this._linkedTxn = new System.Collections.ObjectModel.Collection<LinkedTxn>();
            this._salesOrderLineRet = new System.Collections.ObjectModel.Collection<SalesOrderLineRet>();
            this._salesOrderLineGroupRet = new System.Collections.ObjectModel.Collection<SalesOrderLineGroupRet>();
            this._dataExtRet = new System.Collections.ObjectModel.Collection<DataExtRet>();
            this._shippingDetails = new System.Collections.ObjectModel.Collection<ShippingDetailsLineRet>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<SalesOrderLineRet> _salesOrderLineRet;
        
        [System.Xml.Serialization.XmlElementAttribute("SalesOrderLineRet")]
        public System.Collections.ObjectModel.Collection<SalesOrderLineRet> SalesOrderLineRet
        {
            get
            {
                return _salesOrderLineRet;
            }
            private set
            {
                _salesOrderLineRet = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SalesOrderLineRetSpecified
        {
            get
            {
                return (this.SalesOrderLineRet.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<SalesOrderLineGroupRet> _salesOrderLineGroupRet;
        
        [System.Xml.Serialization.XmlElementAttribute("SalesOrderLineGroupRet")]
        public System.Collections.ObjectModel.Collection<SalesOrderLineGroupRet> SalesOrderLineGroupRet
        {
            get
            {
                return _salesOrderLineGroupRet;
            }
            private set
            {
                _salesOrderLineGroupRet = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SalesOrderLineGroupRetSpecified
        {
            get
            {
                return (this.SalesOrderLineGroupRet.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<DataExtRet> _dataExtRet;
        
        [System.Xml.Serialization.XmlElementAttribute("DataExtRet")]
        public System.Collections.ObjectModel.Collection<DataExtRet> DataExtRet
        {
            get
            {
                return _dataExtRet;
            }
            private set
            {
                _dataExtRet = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataExtRetSpecified
        {
            get
            {
                return (this.DataExtRet.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("FulfillmentStatus")]
        public FulfillmentStatus FulfillmentStatus { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FulfillmentStatusSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ShippingDetailsLineRet> _shippingDetails;
        
        [System.Xml.Serialization.XmlArrayAttribute("ShippingDetails")]
        [System.Xml.Serialization.XmlArrayItemAttribute("ShippingDetailsLineRet")]
        public System.Collections.ObjectModel.Collection<ShippingDetailsLineRet> ShippingDetails
        {
            get
            {
                return _shippingDetails;
            }
            private set
            {
                _shippingDetails = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShippingDetailsSpecified
        {
            get
            {
                return (this.ShippingDetails.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("SOChannel")]
        public SOChannel SOChannel { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SOChannelSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("StoreName")]
        public string StoreName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("StoreType")]
        public string StoreType { get; set; }
    }
}
