//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.718.0 using the following command:
// XmlSchemaClassGenerator -v -n =QBXML -o "C:\Program Files\Intuit\IDN\Common\tools\validator" --sf -dc --dst --da -gc "C:\Program Files\Intuit\IDN\Common\tools\validator\qbxmlops150.xsd"
namespace QBXML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SickHoursDefault", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("SickHoursDefault", Namespace="")]
    public partial class SickHoursDefault
    {
        
        [System.Xml.Serialization.XmlElementAttribute("AccrualPeriod")]
        public AccrualPeriod AccrualPeriod { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccrualPeriodSpecified { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[+\\-]?PT([0-9]+H)?([0-9]+M)?([0-9]+S)?")]
        [System.Xml.Serialization.XmlElementAttribute("HoursAccrued")]
        public string HoursAccrued { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[+\\-]?PT([0-9]+H)?([0-9]+M)?([0-9]+S)?")]
        [System.Xml.Serialization.XmlElementAttribute("MaximumHours")]
        public string MaximumHours { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IsResettingHoursEachNewYear")]
        public string IsResettingHoursEachNewYear { get; set; }
    }
}
