//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.718.0 using the following command:
// XmlSchemaClassGenerator -v -n =QBXML -o "C:\Program Files\Intuit\IDN\Common\tools\validator" --sf -dc --dst --da -gc "C:\Program Files\Intuit\IDN\Common\tools\validator\qbxmlops150.xsd"
namespace QBXML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("UnitOfMeasureSetRet", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("UnitOfMeasureSetRet", Namespace="")]
    public partial class UnitOfMeasureSetRet
    {
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(36)]
        [System.Xml.Serialization.XmlElementAttribute("ListID")]
        public string ListID { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([0-9]{4}\\-[0-9]{1,2}\\-[0-9]{1,2}(T[0-9]{1,2}(:[0-9]{1,2}(:[0-9]{1,2}([+\\-]{1}[0-" +
            "9]{1,2}:[0-9]{1,2})?)?)?)?)?")]
        [System.Xml.Serialization.XmlElementAttribute("TimeCreated")]
        public string TimeCreated { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([0-9]{4}\\-[0-9]{1,2}\\-[0-9]{1,2}(T[0-9]{1,2}(:[0-9]{1,2}(:[0-9]{1,2}([+\\-]{1}[0-" +
            "9]{1,2}:[0-9]{1,2})?)?)?)?)?")]
        [System.Xml.Serialization.XmlElementAttribute("TimeModified")]
        public string TimeModified { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(16)]
        [System.Xml.Serialization.XmlElementAttribute("EditSequence")]
        public string EditSequence { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(31)]
        [System.Xml.Serialization.XmlElementAttribute("Name")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IsActive")]
        public string IsActive { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("UnitOfMeasureType")]
        public UnitOfMeasureType UnitOfMeasureType { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UnitOfMeasureTypeSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("BaseUnit")]
        public BaseUnit BaseUnit { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RelatedUnit> _relatedUnit;
        
        [System.Xml.Serialization.XmlElementAttribute("RelatedUnit")]
        public System.Collections.ObjectModel.Collection<RelatedUnit> RelatedUnit
        {
            get
            {
                return _relatedUnit;
            }
            private set
            {
                _relatedUnit = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RelatedUnitSpecified
        {
            get
            {
                return (this.RelatedUnit.Count != 0);
            }
        }
        
        public UnitOfMeasureSetRet()
        {
            this._relatedUnit = new System.Collections.ObjectModel.Collection<RelatedUnit>();
            this._defaultUnit = new System.Collections.ObjectModel.Collection<DefaultUnit>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<DefaultUnit> _defaultUnit;
        
        [System.Xml.Serialization.XmlElementAttribute("DefaultUnit")]
        public System.Collections.ObjectModel.Collection<DefaultUnit> DefaultUnit
        {
            get
            {
                return _defaultUnit;
            }
            private set
            {
                _defaultUnit = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DefaultUnitSpecified
        {
            get
            {
                return (this.DefaultUnit.Count != 0);
            }
        }
    }
}
