//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.718.0 using the following command:
// XmlSchemaClassGenerator -v -n =QBXML -o "C:\Program Files\Intuit\IDN\Common\tools\validator" --sf -dc --dst --da -gc "C:\Program Files\Intuit\IDN\Common\tools\validator\qbxmlops150.xsd"
namespace QBXML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("VendorAdd", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("VendorAdd", Namespace="")]
    public partial class VendorAdd : IPersonName, ICommInfo
    {
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(41)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Name")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IsActive")]
        public string IsActive { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ClassRef")]
        public ClassRef ClassRef { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(41)]
        [System.Xml.Serialization.XmlElementAttribute("CompanyName")]
        public string CompanyName { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(15)]
        [System.Xml.Serialization.XmlElementAttribute("Salutation")]
        public string Salutation { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(25)]
        [System.Xml.Serialization.XmlElementAttribute("FirstName")]
        public string FirstName { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(5)]
        [System.Xml.Serialization.XmlElementAttribute("MiddleName")]
        public string MiddleName { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(25)]
        [System.Xml.Serialization.XmlElementAttribute("LastName")]
        public string LastName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Suffix")]
        public string Suffix { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(41)]
        [System.Xml.Serialization.XmlElementAttribute("JobTitle")]
        public string JobTitle { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("VendorAddress")]
        public VendorAddress VendorAddress { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ShipAddress")]
        public ShipAddress ShipAddress { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(21)]
        [System.Xml.Serialization.XmlElementAttribute("Phone")]
        public string Phone { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(21)]
        [System.Xml.Serialization.XmlElementAttribute("Mobile")]
        public string Mobile { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(21)]
        [System.Xml.Serialization.XmlElementAttribute("Pager")]
        public string Pager { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(21)]
        [System.Xml.Serialization.XmlElementAttribute("AltPhone")]
        public string AltPhone { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(21)]
        [System.Xml.Serialization.XmlElementAttribute("Fax")]
        public string Fax { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(1023)]
        [System.Xml.Serialization.XmlElementAttribute("Email")]
        public string Email { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(1023)]
        [System.Xml.Serialization.XmlElementAttribute("Cc")]
        public string Cc { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(41)]
        [System.Xml.Serialization.XmlElementAttribute("Contact")]
        public string Contact { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(41)]
        [System.Xml.Serialization.XmlElementAttribute("AltContact")]
        public string AltContact { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AdditionalContactRef> _additionalContactRef;
        
        [System.Xml.Serialization.XmlElementAttribute("AdditionalContactRef")]
        public System.Collections.ObjectModel.Collection<AdditionalContactRef> AdditionalContactRef
        {
            get
            {
                return _additionalContactRef;
            }
            private set
            {
                _additionalContactRef = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdditionalContactRefSpecified
        {
            get
            {
                return (this.AdditionalContactRef.Count != 0);
            }
        }
        
        public VendorAdd()
        {
            this._additionalContactRef = new System.Collections.ObjectModel.Collection<AdditionalContactRef>();
            this._contacts = new System.Collections.ObjectModel.Collection<Contacts>();
            this._additionalNotes = new System.Collections.ObjectModel.Collection<AdditionalNotes>();
            this._prefillAccountRef = new System.Collections.ObjectModel.Collection<PrefillAccountRef>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Contacts> _contacts;
        
        [System.Xml.Serialization.XmlElementAttribute("Contacts")]
        public System.Collections.ObjectModel.Collection<Contacts> Contacts
        {
            get
            {
                return _contacts;
            }
            private set
            {
                _contacts = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ContactsSpecified
        {
            get
            {
                return (this.Contacts.Count != 0);
            }
        }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(41)]
        [System.Xml.Serialization.XmlElementAttribute("NameOnCheck")]
        public string NameOnCheck { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(99)]
        [System.Xml.Serialization.XmlElementAttribute("AccountNumber")]
        public string AccountNumber { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(4095)]
        [System.Xml.Serialization.XmlElementAttribute("Notes")]
        public string Notes { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AdditionalNotes> _additionalNotes;
        
        [System.Xml.Serialization.XmlElementAttribute("AdditionalNotes")]
        public System.Collections.ObjectModel.Collection<AdditionalNotes> AdditionalNotes
        {
            get
            {
                return _additionalNotes;
            }
            private set
            {
                _additionalNotes = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdditionalNotesSpecified
        {
            get
            {
                return (this.AdditionalNotes.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("VendorTypeRef")]
        public VendorTypeRef VendorTypeRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("TermsRef")]
        public TermsRef TermsRef { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([+\\-]?[0-9]{1,13}(\\.[0-9]{2})?)?")]
        [System.Xml.Serialization.XmlElementAttribute("CreditLimit")]
        public string CreditLimit { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(15)]
        [System.Xml.Serialization.XmlElementAttribute("VendorTaxIdent")]
        public string VendorTaxIdent { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IsVendorEligibleFor1099")]
        public string IsVendorEligibleFor1099 { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([+\\-]?[0-9]{1,13}(\\.[0-9]{2})?)?")]
        [System.Xml.Serialization.XmlElementAttribute("OpenBalance")]
        public string OpenBalance { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("OpenBalanceDate")]
        public string OpenBalanceDate { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("BillingRateRef")]
        public BillingRateRef BillingRateRef { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|(\\{[0-9a-fA-F]{8}(\\-([0-9a-fA-F]{4})){3}\\-[0-9a-fA-F]{12}\\})")]
        [System.Xml.Serialization.XmlElementAttribute("ExternalGUID")]
        public string ExternalGUID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("SalesTaxCodeRef")]
        public SalesTaxCodeRef SalesTaxCodeRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("SalesTaxCountry")]
        public SalesTaxCountry SalesTaxCountry { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SalesTaxCountrySpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IsSalesTaxAgency")]
        public string IsSalesTaxAgency { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("SalesTaxReturnRef")]
        public SalesTaxReturnRef SalesTaxReturnRef { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(30)]
        [System.Xml.Serialization.XmlElementAttribute("TaxRegistrationNumber")]
        public string TaxRegistrationNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ReportingPeriod")]
        public ReportingPeriod ReportingPeriod { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReportingPeriodSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IsTaxTrackedOnPurchases")]
        public string IsTaxTrackedOnPurchases { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("TaxOnPurchasesAccountRef")]
        public TaxOnPurchasesAccountRef TaxOnPurchasesAccountRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IsTaxTrackedOnSales")]
        public string IsTaxTrackedOnSales { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("TaxOnSalesAccountRef")]
        public TaxOnSalesAccountRef TaxOnSalesAccountRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IsTaxOnTax")]
        public string IsTaxOnTax { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PrefillAccountRef> _prefillAccountRef;
        
        [System.Xml.Serialization.XmlElementAttribute("PrefillAccountRef")]
        public System.Collections.ObjectModel.Collection<PrefillAccountRef> PrefillAccountRef
        {
            get
            {
                return _prefillAccountRef;
            }
            private set
            {
                _prefillAccountRef = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrefillAccountRefSpecified
        {
            get
            {
                return (this.PrefillAccountRef.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("CurrencyRef")]
        public CurrencyRef CurrencyRef { get; set; }
    }
}
