//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.718.0 using the following command:
// XmlSchemaClassGenerator -v -n =QBXML -o "C:\Program Files\Intuit\IDN\Common\tools\validator" --sf -dc --dst --da -gc "C:\Program Files\Intuit\IDN\Common\tools\validator\qbxmlops150.xsd"
namespace QBXML
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("VendorMod", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("VendorMod", Namespace="")]
    public partial class VendorMod : IListCoreMod, IPersonName, ICommInfo
    {
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(36)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ListID")]
        public string ListID { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(16)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("EditSequence")]
        public string EditSequence { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(41)]
        [System.Xml.Serialization.XmlElementAttribute("Name")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IsActive")]
        public string IsActive { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ClassRef")]
        public ClassRef ClassRef { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(41)]
        [System.Xml.Serialization.XmlElementAttribute("CompanyName")]
        public string CompanyName { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(15)]
        [System.Xml.Serialization.XmlElementAttribute("Salutation")]
        public string Salutation { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(25)]
        [System.Xml.Serialization.XmlElementAttribute("FirstName")]
        public string FirstName { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(5)]
        [System.Xml.Serialization.XmlElementAttribute("MiddleName")]
        public string MiddleName { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(25)]
        [System.Xml.Serialization.XmlElementAttribute("LastName")]
        public string LastName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Suffix")]
        public string Suffix { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(41)]
        [System.Xml.Serialization.XmlElementAttribute("JobTitle")]
        public string JobTitle { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("VendorAddress")]
        public VendorAddress VendorAddress { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ShipAddress")]
        public ShipAddress ShipAddress { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(21)]
        [System.Xml.Serialization.XmlElementAttribute("Phone")]
        public string Phone { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(21)]
        [System.Xml.Serialization.XmlElementAttribute("Mobile")]
        public string Mobile { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(21)]
        [System.Xml.Serialization.XmlElementAttribute("Pager")]
        public string Pager { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(21)]
        [System.Xml.Serialization.XmlElementAttribute("AltPhone")]
        public string AltPhone { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(21)]
        [System.Xml.Serialization.XmlElementAttribute("Fax")]
        public string Fax { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(1023)]
        [System.Xml.Serialization.XmlElementAttribute("Email")]
        public string Email { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(1023)]
        [System.Xml.Serialization.XmlElementAttribute("Cc")]
        public string Cc { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(41)]
        [System.Xml.Serialization.XmlElementAttribute("Contact")]
        public string Contact { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(41)]
        [System.Xml.Serialization.XmlElementAttribute("AltContact")]
        public string AltContact { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AdditionalContactRef> _additionalContactRef;
        
        [System.Xml.Serialization.XmlElementAttribute("AdditionalContactRef")]
        public System.Collections.ObjectModel.Collection<AdditionalContactRef> AdditionalContactRef
        {
            get
            {
                return _additionalContactRef;
            }
            private set
            {
                _additionalContactRef = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdditionalContactRefSpecified
        {
            get
            {
                return (this.AdditionalContactRef.Count != 0);
            }
        }
        
        public VendorMod()
        {
            this._additionalContactRef = new System.Collections.ObjectModel.Collection<AdditionalContactRef>();
            this._contactsMod = new System.Collections.ObjectModel.Collection<ContactsMod>();
            this._additionalNotesMod = new System.Collections.ObjectModel.Collection<AdditionalNotesMod>();
            this._prefillAccountRef = new System.Collections.ObjectModel.Collection<PrefillAccountRef>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ContactsMod> _contactsMod;
        
        [System.Xml.Serialization.XmlElementAttribute("ContactsMod")]
        public System.Collections.ObjectModel.Collection<ContactsMod> ContactsMod
        {
            get
            {
                return _contactsMod;
            }
            private set
            {
                _contactsMod = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ContactsModSpecified
        {
            get
            {
                return (this.ContactsMod.Count != 0);
            }
        }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(41)]
        [System.Xml.Serialization.XmlElementAttribute("NameOnCheck")]
        public string NameOnCheck { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(99)]
        [System.Xml.Serialization.XmlElementAttribute("AccountNumber")]
        public string AccountNumber { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(4095)]
        [System.Xml.Serialization.XmlElementAttribute("Notes")]
        public string Notes { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AdditionalNotesMod> _additionalNotesMod;
        
        [System.Xml.Serialization.XmlElementAttribute("AdditionalNotesMod")]
        public System.Collections.ObjectModel.Collection<AdditionalNotesMod> AdditionalNotesMod
        {
            get
            {
                return _additionalNotesMod;
            }
            private set
            {
                _additionalNotesMod = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdditionalNotesModSpecified
        {
            get
            {
                return (this.AdditionalNotesMod.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("VendorTypeRef")]
        public VendorTypeRef VendorTypeRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("TermsRef")]
        public TermsRef TermsRef { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("([+\\-]?[0-9]{1,13}(\\.[0-9]{2})?)?")]
        [System.Xml.Serialization.XmlElementAttribute("CreditLimit")]
        public string CreditLimit { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(15)]
        [System.Xml.Serialization.XmlElementAttribute("VendorTaxIdent")]
        public string VendorTaxIdent { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IsVendorEligibleFor1099")]
        public string IsVendorEligibleFor1099 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("BillingRateRef")]
        public BillingRateRef BillingRateRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("SalesTaxCodeRef")]
        public SalesTaxCodeRef SalesTaxCodeRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("SalesTaxCountry")]
        public SalesTaxCountry SalesTaxCountry { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SalesTaxCountrySpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IsSalesTaxAgency")]
        public string IsSalesTaxAgency { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("SalesTaxReturnRef")]
        public SalesTaxReturnRef SalesTaxReturnRef { get; set; }
        
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(30)]
        [System.Xml.Serialization.XmlElementAttribute("TaxRegistrationNumber")]
        public string TaxRegistrationNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ReportingPeriod")]
        public ReportingPeriod ReportingPeriod { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReportingPeriodSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IsTaxTrackedOnPurchases")]
        public string IsTaxTrackedOnPurchases { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("TaxOnPurchasesAccountRef")]
        public TaxOnPurchasesAccountRef TaxOnPurchasesAccountRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IsTaxTrackedOnSales")]
        public string IsTaxTrackedOnSales { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("TaxOnSalesAccountRef")]
        public TaxOnSalesAccountRef TaxOnSalesAccountRef { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IsTaxOnTax")]
        public string IsTaxOnTax { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PrefillAccountRef> _prefillAccountRef;
        
        [System.Xml.Serialization.XmlElementAttribute("PrefillAccountRef")]
        public System.Collections.ObjectModel.Collection<PrefillAccountRef> PrefillAccountRef
        {
            get
            {
                return _prefillAccountRef;
            }
            private set
            {
                _prefillAccountRef = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrefillAccountRefSpecified
        {
            get
            {
                return (this.PrefillAccountRef.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("CurrencyRef")]
        public CurrencyRef CurrencyRef { get; set; }
    }
}
